entity_ui.entity_tab.*.*:
  type: config_entity
  label: 'Entity tab config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'The human-readable name of the view mode'
    uuid:
      type: string
    targetEntityType:
      type: string
      label: 'Target entity type'
    verb:
      type: string
      label: 'Permission verb'
    weight:
      type: integer
      label: 'Weight'
